zookeeper:
  image: wurstmeister/zookeeper
  ports:
    - "2181:2181"
kafka:
  image: wurstmeister/kafka:0.8.2.0
  ports:
    - "9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: "kafka"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
kafka-fixed:
  image: wurstmeister/kafka:0.8.2.0
  ports:
    - "9092:9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: "kafka-fixed"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
nakadi:
  image: pierone.stups.zalan.do/laas/aruha-eventstore:0.1-SNAPSHOT
  ports:
    - "8080:8080"
  links:
    - kafka-fixed:kafka
    - zookeeper:zk
  environment:
    KAFKA_BROKER: "kafka:9092,kafka_fixed:9092"
    ZK_BROOKERS: "zk:2181"
